---
scenario:
  name: user
driver:
  name: docker
platforms:
  - name: ansible-role-vim-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    create: ../resources/create.yml
    prepare: prepare.yml
    converge: ../resources/playbook.yml
    destroy: ../resources/destroy.yml
  inventory:
    group_vars:
      all:
        vim_user: testuser
